*** empty log message ***

diff --git a/anivision/configure b/anivision/configure
--- a/anivision/configure
+++ b/anivision/configure
@@ -823,6 +823,8 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-hlib             path to hlib build directory
+  --with-anitmt-build     path to aniTMT build directory
+  --with-anitmt-src       path to aniTMT src directory
 
 Some influential environment variables:
   CC          C compiler command
@@ -4042,6 +4044,78 @@ fi
 # Set hlib's compiler:
 CC="$($hlibdir/HConfigVars CC)"
 CXX="$($hlibdir/HConfigVars CXX)"
+
+# See if we can find anitmt:
+opt_anitmt_build_dir=""
+opt_anitmt_src_dir=""
+
+# Check whether --with-anitmt-build or --without-anitmt-build was given.
+if test "${with_anitmt_build+set}" = set; then
+  withval="$with_anitmt_build"
+  if test "$withval" = "no" ; then
+		opt_anitmt_build_dir=""
+	elif test "$withval" != "yes"; then
+		opt_anitmt_build_dir="$withval"
+	fi
+fi;
+
+# Check whether --with-anitmt-src or --without-anitmt-src was given.
+if test "${with_anitmt_src+set}" = set; then
+  withval="$with_anitmt_src"
+  if test "$withval" = "no" ; then
+		opt_anitmt_src_dir=""
+	elif test "$withval" != "yes"; then
+		opt_anitmt_src_dir="$withval"
+	fi
+fi;
+echo "$as_me:$LINENO: checking for anitmt" >&5
+echo $ECHO_N "checking for anitmt... $ECHO_C" >&6
+anitmt_build_dir=""
+# (build)
+checkdirs="./anitmt ./anitmt-* ../anitmt ../anitmt-*"
+if test "x$opt_anitmt_build_dir" != "x" ; then
+	checkdirs="$opt_anitmt_build_dir $opt_anitmt_build_dir/anitmt $opt_anitmt_build_dir/.."
+fi
+for i in $checkdirs ; do
+  test -e "$i/anitmt-calc/functionality/libfunctionality.a" || continue
+  anitmt_build_dir="$i" ; break
+done
+if test "x$anitmt_build_dir" = "x" ; then
+	echo "$as_me:$LINENO: result: failed" >&5
+echo "${ECHO_T}failed" >&6
+	{ { echo "$as_me:$LINENO: error: Unable to find aniTMT build dir. Giving up." >&5
+echo "$as_me: error: Unable to find aniTMT build dir. Giving up." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+# (source)
+anitmt_src_dir=""
+checkdirs="$anitmt_build_dir ./anitmt ./anitmt-* ../anitmt ../anitmt-*"
+if test "x$opt_anitmt_src_dir" != "x" ; then
+	checkdirs="$opt_anitmt_src_dir $opt_anitmt_src_dir/anitmt $opt_anitmt_src_dir/.."
+fi
+for i in $checkdirs ; do
+  test -e "$i/anitmt-calc/functionality/scalar.afd" || continue
+  anitmt_src_dir="$i" ; break
+done
+if test "x$anitmt_src_dir" = "x" ; then
+	echo "$as_me:$LINENO: result: failed" >&5
+echo "${ECHO_T}failed" >&6
+	{ { echo "$as_me:$LINENO: error: Unable to find aniTMT src dir. Giving up." >&5
+echo "$as_me: error: Unable to find aniTMT src dir. Giving up." >&2;}
+   { (exit 1); exit 1; }; }
+else
+	echo "$as_me:$LINENO: result: src=$anitmt_src_dir, build=$anitmt_build_dir" >&5
+echo "${ECHO_T}src=$anitmt_src_dir, build=$anitmt_build_dir" >&6
+fi
+
+if test "$anitmt_src_dir" != "./anitmt-src" -a "$anitmt_src_dir" != "anitmt-src" ; then
+	test -e "anitmt-src" && rm "anitmt-src"
+	ln -s "$anitmt_src_dir" "anitmt-src"
+fi
+if test "$anitmt_build_dir" != "./anitmt-build" -a "$anitmt_build_dir" != "anitmt-build" ; then
+	test -e "anitmt-build" && rm "anitmt-build"
+	ln -s "$anitmt_build_dir" "anitmt-build"
+fi
 
 # Checks for header files. HLIB already does a lot of these checks, some
 # are repeated here.
